language: python

python:
  - 3.7

services:
  - mongodb

install:
  - pip install -r .requirements
  - pip install coverage codecov
  - pip uninstall -y ujson

script:
  - coverage run --source "sugar_api" --module "unittest" discover --verbose "test"
  - coverage report

after_success:
  - codecov --token "96084111-cd10-408e-bb60-5f4596f60efd"

notifications:

  email: false

  slack:

    rooms:
      - sugarush:ZmgII1nbdMZf6FEhq7PgiuAG#travis-ci

    template:
      - "%{repository_name}@%{branch} commit <%{compare_url}|%{commit}> build <%{build_url}|%{result}>"
      - "%{author}: %{commit_message}"

    on_pull_requests: false
